version: "3"

services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  encoder:
    build: .
    container_name: encoder
    volumes:
      - .:/go/src/
